
[project]
name = "nn-tilde"
version = "2025.0.0"
dependencies = [
  "torch==2.5",
  "cached_conv>=2.5.0"
]
requires-python = ">=3.11"
authors = [
  {name = "Antoine CAILLON"},
  {name = "Axel CHEMLA--ROMEU-SANTOS"},
]
